<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PageController;
use App\Http\Controllers\ThemeController;
use App\Http\Controllers\LayoutController;

Route::get('theme-switcher/{activeTheme}', [ThemeController::class, 'switch'])->name('theme-switcher');
Route::get('layout-switcher/{activeLayout}', [LayoutController::class, 'switch'])->name('layout-switcher');

Route::controller(PageController::class)->group(function () {
    Route::get('/', 'dashboardOverview1')->name('dashboard-overview-1');
    Route::get('/dashboard-overview-2', 'dashboardOverview2')->name('dashboard-overview-2');
    Route::get('/dashboard-overview-3', 'dashboardOverview3')->name('dashboard-overview-3');
    Route::get('/dashboard-overview-4', 'dashboardOverview4')->name('dashboard-overview-4');
    Route::get('/categories', 'categories')->name('categories');
    Route::get('/product-list', 'productList')->name('product-list');
    Route::get('/add-product', 'addProduct')->name('add-product');
    Route::get('/product-grid', 'productGrid')->name('product-grid');
    Route::get('/transaction-list', 'transactionList')->name('transaction-list');
    Route::get('/transaction-detail', 'transactionDetail')->name('transaction-detail');
    Route::get('/seller-list', 'sellerList')->name('seller-list');
    Route::get('/seller-detail', 'sellerDetail')->name('seller-detail');
    Route::get('/reviews', 'reviews')->name('reviews');
    Route::get('/inbox', 'inbox')->name('inbox');
    Route::get('/file-manager', 'fileManager')->name('file-manager');
    Route::get('/point-of-sale', 'pointOfSale')->name('point-of-sale');
    Route::get('/regular-form', 'regularForm')->name('regular-form');
    Route::get('/chat', 'chat')->name('chat');
    Route::get('/regular-table', 'regularTable')->name('regular-table');
    Route::get('/post', 'post')->name('post');
    Route::get('/calendar', 'calendar')->name('calendar');
    Route::get('/crud-data-list', 'crudDataList')->name('crud-data-list');
    Route::get('/crud-form', 'crudForm')->name('crud-form');
    Route::get('/users-layout-1', 'usersLayout1')->name('users-layout-1');
    Route::get('/users-layout-2', 'usersLayout2')->name('users-layout-2');
    Route::get('/users-layout-3', 'usersLayout3')->name('users-layout-3');
    Route::get('/profile-overview-1', 'profileOverview1')->name('profile-overview-1');
    Route::get('/profile-overview-2', 'profileOverview2')->name('profile-overview-2');
    Route::get('/profile-overview-3', 'profileOverview3')->name('profile-overview-3');
    Route::get('/wizard-layout-1', 'wizardLayout1')->name('wizard-layout-1');
    Route::get('/wizard-layout-2', 'wizardLayout2')->name('wizard-layout-2');
    Route::get('/wizard-layout-3', 'wizardLayout3')->name('wizard-layout-3');
    Route::get('/blog-layout-1', 'blogLayout1')->name('blog-layout-1');
    Route::get('/blog-layout-2', 'blogLayout2')->name('blog-layout-2');
    Route::get('/blog-layout-3', 'blogLayout3')->name('blog-layout-3');
    Route::get('/pricing-layout-1', 'pricingLayout1')->name('pricing-layout-1');
    Route::get('/pricing-layout-2', 'pricingLayout2')->name('pricing-layout-2');
    Route::get('/invoice-layout-1', 'invoiceLayout1')->name('invoice-layout-1');
    Route::get('/invoice-layout-2', 'invoiceLayout2')->name('invoice-layout-2');
    Route::get('/faq-layout-1', 'faqLayout1')->name('faq-layout-1');
    Route::get('/faq-layout-2', 'faqLayout2')->name('faq-layout-2');
    Route::get('/faq-layout-3', 'faqLayout3')->name('faq-layout-3');
    Route::get('/login', 'login')->name('login');
    Route::get('/register', 'register')->name('register');
    Route::get('/error-page', 'errorPage')->name('error-page');
    Route::get('/update-profile', 'updateProfile')->name('update-profile');
    Route::get('/change-password', 'changePassword')->name('change-password');
    Route::get('/tabulator', 'tabulator')->name('tabulator');
    Route::get('/dialog', 'dialog')->name('dialog');
    Route::get('/sheet', 'sheet')->name('sheet');
    Route::get('/toast', 'toast')->name('toast');
    Route::get('/tabs', 'tabs')->name('tabs');
    Route::get('/accordion', 'accordion')->name('accordion');
    Route::get('/button', 'button')->name('button');
    Route::get('/alert', 'alert')->name('alert');
    Route::get('/progress', 'progress')->name('progress');
    Route::get('/tooltip', 'tooltip')->name('tooltip');
    Route::get('/dropdown-menu', 'dropdownMenu')->name('dropdown-menu');
    Route::get('/typography', 'typography')->name('typography');
    Route::get('/icon', 'icon')->name('icon');
    Route::get('/easepick', 'easepick')->name('easepick');
    Route::get('/tom-select', 'tomSelect')->name('tom-select');
    Route::get('/dropzone', 'dropzone')->name('dropzone');
    Route::get('/ckeditor-classic', 'ckeditorClassic')->name('ckeditor-classic');
    Route::get('/ckeditor-inline', 'ckeditorInline')->name('ckeditor-inline');
    Route::get('/ckeditor-balloon', 'ckeditorBalloon')->name('ckeditor-balloon');
    Route::get('/ckeditor-balloon-block', 'ckeditorBalloonBlock')->name('ckeditor-balloon-block');
    Route::get('/ckeditor-document', 'ckeditorDocument')->name('ckeditor-document');
    Route::get('/form-validation', 'formValidation')->name('form-validation');
    Route::get('/chart', 'chart')->name('chart');
    Route::get('/slider', 'slider')->name('slider');
    Route::get('/image-zoom', 'imageZoom')->name('image-zoom');
});
